# Generated by Django 5.0.2 on 2024-02-27 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_availeble_product_available'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductManager',
        ),
    ]
